### ISSUE TITLE
Generation with the following .yaml file fails

### ISSUE THREAD

**Issue by mgeeforce** [fujidaiti/fms#2]
```
# ui/esg_symbols.yaml

family: EsgSymbols

output:
  flutter: lib/view/esg_symbols.dart
  font: fonts/esg_symbols.ttf

symbols:
  token: Token

default:
  weight: 300
```

output:
```
Unhandled exception:
type '() => Right<ParseErr, Style>' is not a subtype of type '() => Never' of 'orElse'
#0      None.getOrElse (package:fpdart/src/option.dart)
#1      _parseTheme.<anonymous closure> (package:fms/src/parse/parser.dart:80:14)
#2      _YamlNodeUtils.matchType (package:fms/src/parse/parser.dart:32:59)
#3      _parseTheme (package:fms/src/parse/parser.dart:76:71)
#4      CurryExtension2.curry.<anonymous closure> (package:fpdart/src/function.dart:168:23)
#5      Some.map (package:fpdart/src/option.dart:585:48)
#6      _parseConfig.<anonymous closure> (package:fms/src/parse/parser.dart:195:14)
#7      _YamlNodeUtils.matchType (package:fms/src/parse/parser.dart:32:59)
#8      _parseConfig (package:fms/src/parse/parser.dart:188:62)
#9      TaskEither.chainEither.<anonymous closure> (package:fpdart/src/task_either.dart:52:17)
#10     TaskEither.flatMap.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:fpdart/src/task_either.dart:39:23)
#11     Right.match (package:fpdart/src/either.dart:504:14)
#12     TaskEither.flatMap.<anonymous closure>.<anonymous closure> (package:fpdart/src/task_either.dart:37:38)
<asynchronous suspension>
#13     TaskEither.mapLeft.<anonymous closure> (package:fpdart/src/task_either.dart:87:22)
<asynchronous suspension>
#14     Task.traverseListWithIndexSeq.<anonymous closure> (package:fpdart/src/task.dart:127:23)
<asynchronous suspension>
#15     TaskEither.traverseListWithIndexSeq.<anonymous closure> (package:fpdart/src/task_either.dart:323:11)
<asynchronous suspension>
#16     BuildCommand.run (package:fms/src/command/build.dart:73:5)
<asynchronous suspension>
#17     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#18     main (file:///Users/mike/.pub-cache/hosted/pub.dev/fms-0.9.1/bin/fms.dart:14:3)
<asynchronous suspension>
pub finished with exit code 255
```

**Comment by fujidaiti** [comment]
[This issue](https://github.com/SandroMaglione/fpdart/pull/92) causes the error. Updating `fpdart` to the latest version fixed it.
